title = "gitleaks cloud config"

[extend]
# Extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true


####################################################
# Azure
##

[[rules]]
description = "Azure Service Principal Client Secret"
id = "azure-service-principal-client-secret"
regex = '''(?i)(secret|key|password)\s*:?=?\s*['\"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['\"]'''

[[rules]]
description = "Azure DevOps Personal Access Token"
id = "azure-devops-pat"
regex = '''(?i)(pat|token)\s*:?=?\s*['\"]([a-z0-9]{52})['\"]'''

[[rules]]
description = "Azure Account Key"
id = "azure-account-key"
regex = '''^[a-zA-Z0-9+\/]{86}={0,2}$'''

[[rules]]
description = "Azure Storage Connection String"
id = "azure-storage-account-connection-string"
regex = '''DefaultEndpointsProtocol=https;AccountName=[a-z0-9]{3,24};AccountKey=[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]{88};EndpointSuffix=.+'''

[[rules]]
description = "Azure Cosmos DB Connection String"
id = "azure-cosmos-db-connection-string"
regex = '''AccountEndpoint=https:\/\/.+:443\/;AccountKey=[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]{88};'''


####################################################
# GCP
##

[[rules]]
description = "Google OAuth Access Token"
id = "google-oauth-token"
regex = '''ya29\\.[0-9A-Za-z\\-_]+'''

[[rules]]
description = "GCP API key"
id = "gcp-api-key"
regex = '''(?i)\b(AIza[0-9A-Za-z\\-_]{35})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
keywords = [
    "aiza"
]


####################################################
# Misc
##

[[rules]]
description = "Sensitive environment variable"
id = "sensitive-env-variable"
regex= '''(AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|AMAZON_AWS_ACCESS_KEY_ID|AMAZON_AWS_SECRET_ACCESS_KEY|ALGOLIA_API_KEY|AZURE_CLIENT_ID|AZURE_CLIENT_SECRET|AZURE_USERNAME|AZURE_PASSWORD|MSI_ENDPOINT|MSI_SECRET|binance_api|binance_secret|BITTREX_API_KEY|BITTREX_API_SECRET|CF_PASSWORD|CF_USERNAME|CODECLIMATE_REPO_TOKEN|COVERALLS_REPO_TOKEN|CIRCLE_TOKEN|DIGITALOCEAN_ACCESS_TOKEN|DOCKER_EMAIL|DOCKER_PASSWORD|DOCKER_USERNAME|DOCKERHUB_PASSWORD|FACEBOOK_APP_ID|FACEBOOK_APP_SECRET|FACEBOOK_ACCESS_TOKEN|FIREBASE_TOKEN|FIREBASE_API_TOKEN|FOSSA_API_KEY|GH_TOKEN|GH_ENTERPRISE_TOKEN|CI_DEPLOY_PASSWORD|CI_DEPLOY_USER|GOOGLE_APPLICATION_CREDENTIALS|GOOGLE_API_KEY|CI_DEPLOY_USER|CI_DEPLOY_PASSWORD|GITLAB_USER_LOGIN|CI_JOB_JWT|CI_JOB_JWT_V2|CI_JOB_TOKEN|HEROKU_API_KEY|HEROKU_API_USER|MAILGUN_API_KEY|MCLI_PRIVATE_API_KEY|MCLI_PUBLIC_API_KEY|NGROK_TOKEN|NGROK_AUTH_TOKEN|NPM_AUTH_TOKEN|OKTA_CLIENT_ORGURL|OKTA_CLIENT_TOKEN|OKTA_OAUTH2_CLIENTSECRET|OKTA_OAUTH2_CLIENTID|OKTA_AUTHN_GROUPID|OS_USERNAME|OS_PASSWORD|PERCY_TOKEN|POSTGRES_PASSWORD|SAUCE_ACCESS_KEY|SAUCE_USERNAME|SENTRY_AUTH_TOKEN|SLACK_TOKEN|square_access_token|square_oauth_secret|STRIPE_API_KEY|STRIPE_DEVICE_NAME|SURGE_TOKEN|SURGE_LOGIN|TWILIO_ACCOUNT_SID|CONSUMER_KEY|CONSUMER_SECRET|TRAVIS_SUDO|TRAVIS_OS_NAME|TRAVIS_SECURE_ENV_VARS|TELEGRAM_BOT_TOKEN|VAULT_TOKEN|VAULT_CLIENT_KEY|TOKEN|VULTR_ACCESS|VULTR_SECRET)'''

[[rules]]
description = "JSON Web Token"
id = "jwt"
regex = '''(ey[0-9a-zA-Z]+)\.(ey[0-9a-zA-Z\-\/_]+)\.([0-9a-zA-Z\-\/_]+={0,2})*'''
