apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pv-node-root
  containers:
  - image: <image_name>
    name: privileged
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    volumeMounts:
    - name: host-volume
      mountPath: /host
  restartPolicy: Never