apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app      
  template:
    metadata:
      labels:
        app: my-app    
    spec:
      containers:
      - image: <image_name>
        name: <container_name>
        command: ["/bin/sh", "-c", "sleep infinity"]
        ports:
        - containerPort: <port_number>
