apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  hostPID: true
  hostIPC: true
  hostNetwork: true
  volumes:
  - name: host-volume
    hostPath:
      path: /
  containers:
  - image: <image_name>
    name: privileged
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add: ["SYS_ADMIN", "SYS_MODULE", "SYS_RAWIO", "SYS_CHROOT", "SYS_PTRACE", "SYS_BOOT", "SYSLOG", "NET_ADMIN", "NET_RAW", "DAC_READ_SEARCH"]
    volumeMounts:
    - name: host-volume
      mountPath: /host
  restartPolicy: Never