#### Description ############################################################################
# Purpose:       reverse-engineering a distroless image
# Distribution:  Alpine Linux
####

FROM <name_of_distroless_image>
ADD alpine-minirootfs-3.14.2-x86_64.tar.gz /
USER root
ENTRYPOINT []
